version: '3.7'

services:
  postgres:
    image: postgres:10.7
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    command: >
      -c ssl=on 
      -c ssl_cert_file=/etc/ssl/certs/091aaf2d 
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
  node:
    build:
      context: .
      target: base
    environment:
      APP_NAME: ${APP_NAME}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: "1000:1000"
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
      - "8000:8000"
    volumes:
      - ".:/node:rw"
    command: ["npm", "run", "start:server:dev", "&", "npm", "run", "start:client:dev"]
    links:
      - postgres
    depends_on:
      - "postgres"
volumes:
  postgres_data:
